export const sampleJobs = [
  {
    id: "job-1",
    company: "Boteco Central",
    role: "Garçom",
    neighborhood: "Vila Madalena",
    salary: "R$ 2.100 + gorjeta",
    shift: "Noturno",
    contact: "(11) 90000-1001",
    description: "Atendimento de mesas, organização do salão e apoio no fechamento da casa.",
    status: "published",
    created_at: "2026-06-01T12:00:00.000Z",
  },
  {
    id: "job-2",
    company: "Cantina Boa Massa",
    role: "Auxiliar de cozinha",
    neighborhood: "Centro",
    salary: "R$ 1.850 + VT",
    shift: "Escala 6x1",
    contact: "rh@boamassa.com",
    description: "Pré-preparo, higienização de alimentos e apoio ao cozinheiro principal.",
    status: "published",
    created_at: "2026-06-02T12:00:00.000Z",
  },
  {
    id: "job-3",
    company: "Bar do Mercado",
    role: "Bartender freelancer",
    neighborhood: "Mooca",
    salary: "R$ 180 por diária",
    shift: "Fim de semana",
    contact: "(11) 98888-2020",
    description: "Preparo de drinks clássicos, controle do balcão e atendimento direto ao cliente.",
    status: "published",
    created_at: "2026-06-03T12:00:00.000Z",
  },
];

export const sampleResumes = [
  {
    id: "resume-1",
    name: "Mariana Costa",
    phone: "(11) 97777-4444",
    desired_role: "Recepcionista",
    neighborhood: "Pinheiros",
    experience: "3 anos em atendimento, reservas, caixa e organização de salão.",
    status: "new",
    created_at: "2026-06-04T12:00:00.000Z",
  },
  {
    id: "resume-2",
    name: "Rafael Lima",
    phone: "(11) 96666-3030",
    desired_role: "Chapeiro",
    neighborhood: "Tatuapé",
    experience: "Experiência com lanches, porções, mise en place e limpeza de praça.",
    status: "new",
    created_at: "2026-06-04T12:00:00.000Z",
  },
];
